---
sudo: required
language: python
python:
  - "2.7"
services:
  - docker

env:
  matrix:
    - ANS_VER=2.6.3 OS_TYPE=centos OS_VER=7.4.1708 INIT=/sbin/init
    - ANS_VER=2.6.3 OS_TYPE=centos OS_VER=7.3.1611 INIT=/sbin/init
    - ANS_VER=2.6.3 OS_TYPE=centos OS_VER=7.5.1804 INIT=/sbin/init
#    - ANS_VER=2.6.4 OS_TYPE=centos OS_VER=7.4.1708 INIT=/sbin/init
#    - ANS_VER=2.6.3 OS_TYPE=centos OS_VER=6.10     INIT="tail -f /dev/null"

before_install:
  # Prepare Travis environment
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - export CON_ID=$(date +%s)
  - export INV_FILE=${PWD}/inventory

  # Install Ansible
  - sudo pip install -U pip setuptools
  - sudo pip install ansible==${ANS_VER}

  # Prepare test container
  - docker run -d --privileged --name ${CON_ID} ${OS_TYPE}:${OS_VER} ${INIT}
  - echo ${CON_ID} > ${INV_FILE}

script:
  # Show test environment
  - ansible --version
  - ansible all -c docker -m setup -a 'filter=ansible_distribution*'

  # Run tests
  - ansible-playbook web_svr/tests/test.yml --syntax-check
  - ansible-playbook web_svr/tests/test.yml -c docker -v

notifications:
  email: false
